name: Deploy to Server

on:
  workflow_run:
    workflows: ["PHP Lint and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key and deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.SSH_PASS }}
          debug: true
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://asimbsit: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@github.com/asimbsit/ci_cd_php.git
            fi
            git pull origin dev
