name: Deploy to Server

on:
  workflow_run:
    workflows: ["PHP Lint and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key and deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            whoami
            ls -l
            cd ${{ secrets.DEPLOY_PATH }}
            if [ ! -d ".git" ]; then
              git init
              git remote add origin <repository-url>
            fi
            git pull origin dev
