name: Deploy to Server

on:
  # workflow_run:
  #   workflows: ["PHP Lint and Test"]
  #   types:
  #     - completed
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.conclusion == 'success' }}
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key and deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{ secrets.DEPLOY_SERVER }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.SSH_PASS }}
          debug: true
          script: |
            cd ${{ secrets.DEPLOY_PATH }}
            if [ ! -d ".git" ]; then
              git init
              git remote add origin ${{ secrets.SSH_GIT_ORIGIN_WITH_PAT }}
            fi
            git pull origin dev
