name: Deploy to Server

on:
  workflow_run:
    workflows: ["PHP Lint and Test"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -x  # Enable debugging

          # Create .ssh directory
          mkdir -p ~/.ssh

          # Output SSH key and permissions
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh  # List .ssh directory to confirm id_rsa file permissions

          # Scan SSH key with verbose output
          ssh-keyscan -p $DEPLOY_PORT -H $DEPLOY_SERVER || true  # Ignore errors to see output

          # Test SSH connection with verbose output
          ssh -o StrictHostKeyChecking=no -p $DEPLOY_PORT $DEPLOY_USER@$DEPLOY_SERVER "echo SSH connection successful" || true

          # Run rsync with verbose output
          rsync -avz -e "ssh -p $DEPLOY_PORT -v" --exclude '.git*' . $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH || true
