name: PHP Lint and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run PHP syntax check
        run: |
            set -e
            exit_code=0
            find . -path ./vendor -prune -o -type f -name "*.php" -exec php -l {} \; || exit_code=$?
            if [ $exit_code -ne 0 ]; then
              echo "Syntax errors detected"
              exit 1
            fi
                 
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Specify your PHP version here

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --verbose tests

