name: PHP Lint and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run PHP syntax check
        run: |
          set -e
          # Initialize a variable to track errors
          error_detected=0
          # Find all PHP files excluding vendor directory and check syntax
          find . -path ./vendor -prune -o -type f -name "*.php" -exec php -l {} \; | while read -r line; do
            echo "start"
            echo "$line"
            echo "end"
            if echo "$line" | grep -q "Parse error"; then
              echo "I am in the condition"
            fi
          done
          exit 1
                 
      # - name: Set up PHP
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: '7.4' # Specify your PHP version here

      # - name: Install dependencies
      #   run: composer install

      # - name: Run PHPUnit tests
      #   run: ./vendor/bin/phpunit --verbose tests

