name: PHP Lint and Test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run PHP syntax check
        run: |
          set -e
          # Initialize a variable to track errors
          error_detected=0
          # Find all PHP files excluding vendor directory and check syntax
          find . -path ./vendor -prune -o -type f -name "*.php" -exec php -l {} \; 2>&1 | while read -r line; do
            if echo "$line" | grep -q "Parse error"; then
              echo "$line"
              exit 1
            fi
          done
          
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4' # Specify your PHP version here

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit tests
        run: ./vendor/bin/phpunit --verbose tests

